---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    environment: {container: docker}
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - destroy

verifier:
  name: ansible

lint: |
  yamllint .
  ansible-lint .
