---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install test dependencies
        run: pip3 install yamllint ansible-lint

      - name: Yamllint
        run: |
          yamllint .

      - name: Ansible-lint
        run: |
          ansible-lint .

  molecule:
    name: Molecule
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu2204
          - ubuntu2404

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install dependencies.
        run: pip3 install -r ./molecule/requirements.txt

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
